2 task components
otecpavlo/youtube-client pull request #3
Opened 2021-08-10 13:57 UTC by otecpavlo

1. Task: https://github.com/rolling-scopes-school/tasks/blob/master/tasks/angular/components-directives-pipes.md
2. Screenshot:
   ![Imgur](https://i.imgur.com/unQ5G11.png)
3. Deploy: https://otecpavlo.github.io/youtube-client/youtube-client/bundle/
4. Done10.08.2021 / deadline 08.08.2021
:heavy_check_mark: Main layout is implemented
:heavy_check_mark: Implemented a fake search functionality: by submitting the form on the Header component, search results are shown
:heavy_check_mark: The Search result item component contains all the necessary data 
:heavy_check_mark: The Filtering criteria block toggle functionality is implemented
:heavy_check_mark: The colorful border under the Search result item is implemented 
:heavy_check_mark: Search result sorting is implemented (Should work both in the direction of decreasing values, and in the direction of increasing values) 
:heavy_check_mark: Search result filtering by key words is implemented

2021-08-14 09:17 UTC, 4m9fk requested changes

2021-08-14 09:17 UTC, 4m9fk commented on youtube-client/src/app/services/search-service.ts
> +        response.items.forEach((item) => {
You should use `map` for it.
```ts
this.searchItems = response.items.map( item => ({...}))
```

2021-08-14 09:17 UTC, 4m9fk commented on youtube-client/src/app/services/search-service.ts
> +  sortByViews(directionToBottom: boolean) {
Let's use pipe for sorting and filtering.
You can check example here https://github.com/ppparfenovich/youtube-client/pull/2/files#diff-f5dbdfa92848dde3da3141f676253d75d351cdb029db006226240c8ac8dd285c

2021-08-14 09:17 UTC, 4m9fk commented on youtube-client/src/app/search-result/directives/colorful-border.directive.ts
> +export class ColorfulBorderDirective implements OnInit {
Great that you used directive!

2021-08-14 09:17 UTC, 4m9fk commented on youtube-client/src/app/search-result/search-result-item/search-result-item.component.scss
> +// .comments-icon__span {
PLease remove commented code

2021-08-14 09:17 UTC, 4m9fk commented on youtube-client/src/app/search-result/search-result-item/search-result-item.component.ts
> +  @Input() item!: ISearchItem;
Please avoid `!` usage

2021-08-15 05:32 UTC, otecpavlo commented on youtube-client/src/app/search-result/search-result-item/search-result-item.component.scss
> +// .comments-icon__span {
removed

2021-08-15 05:41 UTC, otecpavlo commented on youtube-client/src/app/search-result/search-result-item/search-result-item.component.ts
> +  @Input() item!: ISearchItem;
`!` removed

2021-08-15 05:44 UTC, otecpavlo commented on youtube-client/src/app/services/search-service.ts
> +  sortByViews(directionToBottom: boolean) {
added sort and filter pipes

2021-08-15 05:44 UTC, otecpavlo commented on youtube-client/bundle/3rdpartylicenses.txt
> +@angular/common
fixed

2021-08-15 05:44 UTC, otecpavlo commented on youtube-client/src/app/services/search-service.ts
> +        response.items.forEach((item) => {
fixed

2021-08-17 11:48 UTC, closed without merging